services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped